services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # External services port range
    environment:
      - SERVICES=lambda,dynamodb,s3,apigateway,iam,cloudwatch,logs
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=60
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.build:/tmp/lambda-builds"
    networks:
      - localstack-network

networks:
  localstack-network:
    driver: bridge
